// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQiIhFrX1jXHHfPECJkcE9ymN7SYOrHw',
    appId: '1:257017510484:web:444a16ab03d4e15fef8bc1',
    messagingSenderId: '257017510484',
    projectId: 'autism-a8f89',
    authDomain: 'autism-a8f89.firebaseapp.com',
    storageBucket: 'autism-a8f89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7k4YN2G1V2sHzKRxkAv5ooDsMrgdehs',
    appId: '1:257017510484:android:f17453e89480f43eef8bc1',
    messagingSenderId: '257017510484',
    projectId: 'autism-a8f89',
    storageBucket: 'autism-a8f89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPYx2OwwbLm4TKl7PvkuKdnG9yiNWnmr0',
    appId: '1:257017510484:ios:b4cce8f7525083a3ef8bc1',
    messagingSenderId: '257017510484',
    projectId: 'autism-a8f89',
    storageBucket: 'autism-a8f89.firebasestorage.app',
    iosBundleId: 'com.example.appAutismDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPYx2OwwbLm4TKl7PvkuKdnG9yiNWnmr0',
    appId: '1:257017510484:ios:b4cce8f7525083a3ef8bc1',
    messagingSenderId: '257017510484',
    projectId: 'autism-a8f89',
    storageBucket: 'autism-a8f89.firebasestorage.app',
    iosBundleId: 'com.example.appAutismDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZQiIhFrX1jXHHfPECJkcE9ymN7SYOrHw',
    appId: '1:257017510484:web:93d233b81c157a22ef8bc1',
    messagingSenderId: '257017510484',
    projectId: 'autism-a8f89',
    authDomain: 'autism-a8f89.firebaseapp.com',
    storageBucket: 'autism-a8f89.firebasestorage.app',
  );
}